In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)

 ### 1 How likely is it that you roll doubles when rolling two dice?


In [2]:
n_trials = nrows = 100_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [5, 6],
       [5, 5],
       [6, 5]])

In [3]:
#Converting the arrasy into a dataframe 
df = pd.DataFrame(rolls)

In [4]:
# determerning where each row value in column 1 matches the the row value in column 2 and finding the mean
(df[0] == df[1]).mean()

0.16645

### 2 If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
# setting uop the number of trials and and number of coin flips per trial
n_trials2 = nrows = 100_000
n_flips = ncols = 8 

# head is 1 and tail 0
flips = np.random.choice([0,1], n_trials2 * n_flips).reshape(nrows, ncols)



In [6]:
flips 

array([[1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 1, 0]])

In [7]:
# finding where each row has exactly 3 heads per flips, then finding the probaility
(flips.sum(axis=1) ==3).mean()

0.2188

In [8]:
flips.sum(axis=1)

array([4, 5, 2, ..., 3, 3, 3])

In [37]:
# finding where each row has more than 3 heads per flips, then finding the probaility

(flips.sum(axis=1) >3).mean()

0.63588

### 3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?



In [10]:
# lets use 0 for Web Dev and 1 for data science
np.random.choice([0,1], p =(0.75, 0.25))

0

In [38]:
n_trials = 100_000
n_billboard = 2

billboard = np.random.choice([0, 1], p=[.75, .25], size=(n_trials, n_billboard))
billboard = pd.DataFrame(billboard)
billboard.head()

0  1
0  0  0
1  0  1
2  0  1
3  0  0
4  1  0

In [39]:
 # lets find the possiblity of having data science studnt on both billbords
(billboard.sum(axis=1) ==2).mean()

0.06388

### 4 Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [32]:
n_rows = 100_000

ncols = 5

rolls = np.random.normal(3,1.5, n_rows * ncols).astype(int).reshape(n_rows, ncols)


df = pd.DataFrame(rolls)

df.head(5)

0  1  2  3  4
0  3  2  2  3  5
1  1  1  4  2  3
2  2  3  6  4  2
3  2  3  1 -1  2
4  4  2  2  4  3

In [35]:
odds = df.apply(lambda row: row.values.sum() < 17, axis=1).mean()

In [36]:
odds

0.87855

### 5 Compare Heights

 - Men have an average height of 178 cm and standard deviation of 8cm.
 - Women have a mean of 170, sd = 6cm.
 - Since you have means and standard deviations, you can use np.random.normal to generate observations.
 - If a man and woman are chosen at random, P(woman taller than man)?

In [46]:
men_heights = np.random.normal(178, 8, 100_000)
women_heights = np.random.normal(170, 6, 100_000)

In [47]:
df = pd.DataFrame({'men_heights':men_heights, 'women_heights': women_heights})
df['woman_is_taller'] = df['women_heights'] > df['men_heights']


df

men_heights  women_heights  woman_is_taller
0       174.000669     170.408757            False
1       168.013373     168.526825             True
2       180.497126     166.057511            False
3       187.611419     172.701316            False
4       183.274299     154.929990            False
...            ...            ...              ...
99995   181.464613     167.543139            False
99996   183.070324     159.885632            False
99997   165.981355     168.142515             True
99998   187.350336     170.636288            False
99999   183.774714     169.446837            False

[100000 rows x 3 columns]

In [48]:
# probability of woman chosen at random being taller 

df.woman_is_taller.mean()

0.21162

### 6 When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

###  instructor's review ***

- What is the probability that we observe an installation issue within the first 150 students that download anaconda?

- How likely is it that 450 students all download anaconda without an issue?

In [49]:
def anaconda_problem(number_of_students):
    
    nrows = 100_000 # set rows to number of simulations
    ncols = number_of_students # set columns to number of students in each simulation

    # create list with 249 falses and one true
    issue_range = [False for r in range(1,250)]
    issue_range.append(True)

    # use random.choice to create an arrepresenting whether there was an issue with a given student's Anaconda install
    # reshape the dataframe into trial groups of the desiered number of students
    installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

    # convert to data frame
    df = pd.DataFrame(installs)

    # Sum the number of True values in each row (trial) 
    # create a boolian array that shows true for each row (trial) that had no Trues
    # Take the mean of that array to get the odds of not encountering any problems in the trial group
    no_problems = df.apply(lambda row: row.values.sum() == 0, axis=1).mean()
    
    # Sum the number of True values in each row (trial) 
    # create a boolian array that shows true for each row (trial) that had no Trues
    # Take the mean of that array to get the odds encountering any problems in the trial group
    problems = df.apply(lambda row: row.values.sum() > 0, axis=1).mean()

    print(f'The odds of {number_of_students} students downloading Anaconda without a problem are {round(no_problems*100)}%')
    print(f'The odds of {number_of_students} students downloading Anaconda encountering at least one problem are {round(problems*100)}%')

In [50]:
#What are the odds that after having 50 students download anaconda, no one has an installation issue?
anaconda_problem(50)


The odds of 50 students downloading Anaconda without a problem are 82%
The odds of 50 students downloading Anaconda encountering at least one problem are 18%


In [51]:
##What are the odds that after having 100 students download anaconda, no one has an installation issue?

anaconda_problem(100)

The odds of 100 students downloading Anaconda without a problem are 67%
The odds of 100 students downloading Anaconda encountering at least one problem are 33%


In [52]:
# What is the probability that we observe an installation issue within the first 150 students that download anaconda?¶

anaconda_problem(150)

The odds of 150 students downloading Anaconda without a problem are 55%
The odds of 150 students downloading Anaconda encountering at least one problem are 45%


In [53]:
#How likely is it that 450 students all download anaconda without an issue?
anaconda_problem(450)

The odds of 450 students downloading Anaconda without a problem are 17%
The odds of 450 students downloading Anaconda encountering at least one problem are 83%


### 7 There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?¶

###  instuctor's review ***
- How likely is it that a food truck will show up sometime this week?

In [54]:
def food_truck(days):
    
    # Remaining week days
    nrows = 100_000 # set rows to number of simulations
    ncols = days      # set columns to number of days in each simulation

    # create array with each value representing if a food truck has been spotted that day
    # reshape the array into trial groups of the desiered number of days
    sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)

    # convert to data frame
    df = pd.DataFrame(sightings)

    # Sum the number of True values in each row (trial) 
    # create a boolian array that shows true for each row (trial) that had no Trues
    # Take the mean of that array to get the odds of not encountering any trucks in the specified number of days
    no_truck = df.apply(lambda row: row.values.sum() == 0, axis=1).mean()
    
    # Sum the number of True values in each row (trial) 
    # create a boolian array that shows true for each row (trial) that had no Trues
    # Take the mean of that array to get the odds spotting at least one tuck in the desiered number of days
    truck = df.apply(lambda row: row.values.sum() > 0, axis=1).mean()

    print(f'The odds of not seeing a food truck in Travis Park for {days} days is {round(no_truck*100)}%')
    print(f'The odds of seeing at least one food truck in Travis Park in {days} days is {round(truck*100)}%')

In [55]:
for r in range(1,8):
    food_truck(r)
    print()

The odds of not seeing a food truck in Travis Park for 1 days is 30%
The odds of seeing at least one food truck in Travis Park in 1 days is 70%

The odds of not seeing a food truck in Travis Park for 2 days is 9%
The odds of seeing at least one food truck in Travis Park in 2 days is 91%

The odds of not seeing a food truck in Travis Park for 3 days is 3%
The odds of seeing at least one food truck in Travis Park in 3 days is 97%

The odds of not seeing a food truck in Travis Park for 4 days is 1%
The odds of seeing at least one food truck in Travis Park in 4 days is 99%

The odds of not seeing a food truck in Travis Park for 5 days is 0%
The odds of seeing at least one food truck in Travis Park in 5 days is 100%

The odds of not seeing a food truck in Travis Park for 6 days is 0%
The odds of seeing at least one food truck in Travis Park in 6 days is 100%

The odds of not seeing a food truck in Travis Park for 7 days is 0%
The odds of seeing at least one food truck in Travis Park in 7 da

### 8) If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?¶

### Instructor's review ***

In [56]:
def shared_birthday(people):

    nrows = 100_000 # set rows to number of simulations
    ncols = people  # set columns to number of people in each simulation

    # create array with each value representing the numbered day of the year that person was born on. (This ignores leap years)
    # reshape the aray into trial groups
    sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

    # convert to data frame
    df = pd.DataFrame(sightings)

    # Add boolian column to df showing weather there are less unique numbers in each row (trial) than there are total columns
    df['matching_birthdays'] = df.nunique(axis=1) < ncols

    # get mean of calculation True/False columns
    # format and print results
    matching_birthdays = df['matching_birthdays'].mean()

    # print result
    print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {round(matching_birthdays*100)}%')

In [57]:
num_list = [23, 20, 40]

for num in num_list:
    shared_birthday(num)

The odds of a room of 23 people having at least two people that share a birthday are 51%
The odds of a room of 20 people having at least two people that share a birthday are 41%
The odds of a room of 40 people having at least two people that share a birthday are 89%
